[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/1_ğŸ _Obras.py"
name = "Obras"
icon = "ğŸ "

[[pages]]
path = "pages/2_ğŸ‘¥_Clientes.py"
name = "Clientes"
icon = "ğŸ‘¥"

[[pages]]
path = "pages/3_ğŸ‘·_Pessoas.py"
name = "Pessoas"
icon = "ğŸ‘·"

[[pages]]
path = "pages/4_ğŸ“‹_Orcamentos.py"
name = "OrÃ§amentos"
icon = "ğŸ“‹"

[[pages]]
path = "pages/5_ğŸ“…_Agenda.py"
name = "Agenda"
icon = "ğŸ“…"

[[pages]]
path = "pages/6_ğŸ’°_Financeiro.py"
name = "Financeiro"
icon = "ğŸ’°"

[[pages]]
path = "pages/7_âš™ï¸_Configuracoes.py"
name = "ConfiguraÃ§Ãµes"
icon = "âš™ï¸"
